/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;
import model.Jogo;
import model.FormaPGTO;
import model.Locacao;
import model.Util;
import model.dao.ClienteDAO;
import model.dao.FuncionarioDAO;
import model.dao.JogoDAO;

/**
 *
 * @author Jonathan
 */
public class CadastroLocacaoJD extends javax.swing.JDialog {
    
    Locacao locacao;
    
    ClienteDAO daoCliente;
    FuncionarioDAO daoFuncionario;
    JogoDAO daoJogo;

    /**
     * Creates new form CadastroLocacaoJD
     */
    public CadastroLocacaoJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        daoCliente = new ClienteDAO();
        daoFuncionario = new FuncionarioDAO();
        daoJogo = new JogoDAO();
        
        loadClientes();
        loadFuncionarios();
        loadJogos();
        
        loadPGTO();
        
        txtData.setText(Util.formatDateTime(LocalDateTime.now()));
    }
    
    public void loadClientes() {
        for (Cliente c: daoCliente.listaClientes()) {
            cmbCliente.addItem(c);
        }
    }
    
    public void loadFuncionarios() {
        for (Funcionario f: daoFuncionario.listaFuncionarios()) {
            cmbFuncionario.addItem(f);
        }
    }
    
    public void loadJogos() {
        for (Jogo j: daoJogo.listaJogos()) {
            cmbJogo.addItem(j);
        }
    }
    
    public void loadPGTO() {
        for (FormaPGTO pgto: FormaPGTO.values()) {
            cmbPGTO.addItem(pgto);
        }
    }
    
    public Locacao getLocacao() {
        return locacao;
    }
    public void setLocacao(Locacao locacao) {
        this.locacao = locacao;
        
        cmbCliente.setSelectedItem(locacao.getCliente());
        cmbJogo.setSelectedItem(locacao.getProduto());
        cmbFuncionario.setSelectedItem(locacao.getVendedor());
        txtValor.setText(Util.formatDouble(locacao.getValor()));
        txtData.setText(Util.formatDateTime(locacao.getDataLocacao()));
        txtPrazo.setText(String.valueOf(locacao.getPrazo()));
        txtDevolucao.setText(Util.formatDateTime(locacao.getDataDevolucao()));
        cmbPGTO.setSelectedItem(locacao.getPgto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        lblJogo = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblPrazo = new javax.swing.JLabel();
        lblDevolucao = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbJogo = new javax.swing.JComboBox<>();
        cmbFuncionario = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtPrazo = new javax.swing.JTextField();
        txtDevolucao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPGTO = new javax.swing.JLabel();
        cmbPGTO = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCliente.setText("Cliente");

        lblJogo.setText("Jogo");

        lblFuncionario.setText("Funcionário");

        lblValor.setText("Valor");

        lblData.setText("Data");

        lblPrazo.setText("Prazo");

        lblDevolucao.setText("Devolucao");

        cmbJogo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJogoItemStateChanged(evt);
            }
        });

        txtPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrazoActionPerformed(evt);
            }
        });
        txtPrazo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrazoPropertyChange(evt);
            }
        });

        txtDevolucao.setEditable(false);
        txtDevolucao.setBackground(new java.awt.Color(204, 204, 204));
        txtDevolucao.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPGTO.setText("Forma de Pagamento");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Locação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addComponent(lblJogo)
                            .addComponent(lblFuncionario)
                            .addComponent(lblValor)
                            .addComponent(lblData)
                            .addComponent(lblPrazo)
                            .addComponent(lblDevolucao)
                            .addComponent(lblPGTO))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPGTO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDevolucao)
                            .addComponent(txtPrazo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbJogo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJogo)
                    .addComponent(cmbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrazo)
                    .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevolucao)
                    .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPGTO)
                    .addComponent(cmbPGTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbJogoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJogoItemStateChanged
        Jogo objSel = (Jogo) cmbJogo.getSelectedItem();
        if (objSel != null) {
            txtValor.setText(Util.formatDouble(objSel.getValor()));
        }
    }//GEN-LAST:event_cmbJogoItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (locacao == null)
                locacao = new Locacao();
            
            Jogo produto = (Jogo) cmbJogo.getSelectedItem();
            double valor = Double.parseDouble(txtValor.getText().replace(",", "."));
            LocalDateTime data = LocalDateTime.parse(txtData.getText(), Util.getDateTimeF());
            LocalDateTime devolucao = LocalDateTime.parse(txtDevolucao.getText(), Util.getDateTimeF());
            
            if (produto.isLocado()) {
                locacao = null;
                JOptionPane.showMessageDialog(rootPane, "Ops, este jogo já está locado!");
                return;
            }
            
            locacao.setCliente((Cliente) cmbCliente.getSelectedItem());
            locacao.setProduto(produto);
            locacao.setVendedor((Funcionario) cmbFuncionario.getSelectedItem());
            locacao.setValor(valor);
            locacao.setDataLocacao(data);
            locacao.setPrazo(Integer.parseInt(txtPrazo.getText()));
            locacao.setDataDevolucao(devolucao);
            locacao.setPgto((FormaPGTO) cmbPGTO.getSelectedItem());
            
            locacao.getProduto().setLocado(devolucao.isAfter(LocalDateTime.now()));
            daoJogo.persist(locacao.getProduto());
            
            this.dispose();
        } catch (Exception e) {
            locacao = null;
            JOptionPane.showMessageDialog(rootPane, "Algo deu errado!\n" + e);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrazoActionPerformed
        LocalDateTime data = LocalDateTime.parse(txtData.getText(), Util.getDateTimeF()).withHour(23).withMinute(59).withSecond(59).withNano(0);
        data = data.plusDays(Long.parseLong(txtPrazo.getText()));
        txtDevolucao.setText(Util.formatDateTime(data));
    }//GEN-LAST:event_txtPrazoActionPerformed

    private void txtPrazoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrazoPropertyChange
       
    }//GEN-LAST:event_txtPrazoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroLocacaoJD dialog = new CadastroLocacaoJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cmbCliente;
    private javax.swing.JComboBox<Funcionario> cmbFuncionario;
    private javax.swing.JComboBox<Jogo> cmbJogo;
    private javax.swing.JComboBox<FormaPGTO> cmbPGTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblJogo;
    private javax.swing.JLabel lblPGTO;
    private javax.swing.JLabel lblPrazo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDevolucao;
    private javax.swing.JTextField txtPrazo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
